### ISSUE TITLE
Création Item : bad gateway

### ISSUE THREAD

**Issue by mnauge** [Francoralite/francoralite#169]
J'essai de créer des items dans cette l'enquete :Enquête : Debug-Répertoire chanté et témoignages de Marie-Henriette Ricou ; Charles Aubrière et Mme Aubrière – La Michelière 1969 

https://app.preprod.francoralite.net/collection/38

où je pose un petit fichier MP3. Je valide, ça n'affiche pas d'erreur. Mais quand je souhaite consulter l'item, j'ai un badgateway... 
Bug ou erreur de saisie de mon côté ?
https://app.preprod.francoralite.net/item/80

**Comment by lluc** [comment]
Dans les logs , on observe ceci : 
```
[874] [ERROR] Socket error processing request.
app_1          | Traceback (most recent call last):
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
app_1          |     self.handle_request(listener, req, client, addr)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 191, in handle_request
app_1          |     six.reraise(*sys.exc_info())
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
app_1          |     respiter = self.wsgi(environ, resp.start_response)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
app_1          |     response = self.get_response(request)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
app_1          |     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/handlers/base.py", line 256, in handle_uncaught_exception
app_1          |     'request': request
app_1          |   File "/opt/miniconda/lib/python2.7/logging/__init__.py", line 1200, in error
app_1          |     self._log(ERROR, msg, args, **kwargs)
app_1          |   File "/opt/miniconda/lib/python2.7/logging/__init__.py", line 1293, in _log
app_1          |     self.handle(record)
app_1          |   File "/opt/miniconda/lib/python2.7/logging/__init__.py", line 1303, in handle
app_1          |     self.callHandlers(record)
app_1          |   File "/opt/miniconda/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
app_1          |     hdlr.handle(record)
app_1          |   File "/opt/miniconda/lib/python2.7/logging/__init__.py", line 766, in handle
app_1          |     self.emit(record)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/log.py", line 129, in emit
app_1          |     self.send_mail(subject, message, fail_silently=True, html_message=html_message)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/utils/log.py", line 132, in send_mail
app_1          |     mail.mail_admins(subject, message, *args, connection=self.connection(), **kwargs)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/mail/__init__.py", line 98, in mail_admins
app_1          |     mail.send(fail_silently=fail_silently)
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/mail/message.py", line 303, in send
app_1          |     return self.get_connection(fail_silently).send_messages([self])
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
app_1          |     new_conn_created = self.open()
app_1          |   File "/opt/miniconda/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 58, in open
app_1          |     self.connection = connection_class(self.host, self.port, **connection_params)
app_1          |   File "/opt/miniconda/lib/python2.7/smtplib.py", line 256, in __init__
app_1          |     (code, msg) = self.connect(host, port)
app_1          |   File "/opt/miniconda/lib/python2.7/smtplib.py", line 317, in connect
app_1          |     self.sock = self._get_socket(host, port, self.timeout)
app_1          |   File "/opt/miniconda/lib/python2.7/smtplib.py", line 292, in _get_socket
app_1          |     return socket.create_connection((host, port), timeout)
app_1          |   File "/opt/miniconda/lib/python2.7/socket.py", line 575, in create_connection
app_1          |     raise err
app_1          | error: [Errno 101] Network is unreachable

```

C'est simultané à l'affichage de l'erreur "_502 badgateway_".  
Je n'arrive pas à déterminer le lien de l'erreur, pour le moment. :thinking:

**Comment by lluc** [comment]
Ce phénomène est présent pour tous les items de **cette enquête**.

**Comment by mnauge** [comment]
Peux-tu essayer de créer une nouvelle enquête et d'y ajouter un item ?

**Comment by lluc** [comment]
J'ai failli te le suggérer ...   ;-)
Je vais donc essayer avec ton profil.

**Comment by lluc** [comment]
Création d'une enquête : https://app.preprod.francoralite.net/collection/42
Création d'un item : https://app.preprod.francoralite.net/item/82

--> même souci.  :-(

**Comment by lluc** [comment]
:mag_right:  Dans  _francoralite/apps/francoralite_front/templates/item-detail.html_ `{{url_external}}` ne semble pas correct.

**Comment by mnauge** [comment]
C'est bon, j'ai pu créer un nouvel item ! ouff :-)
